name: CI/CD with EC2 Self-hosted Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Self-hosted Runner 사용

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      # 3. 배포 스크립트 실행 (EC2 안에서)
      - name: Run deploy.sh
        run: |
          cd /home/ec2-user/app/step2
          chmod +x deploy.sh
          ./deploy.sh